apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app
  namespace: dev-app
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: app # имя SecretStore
    kind: SecretStore
  target:
    name: vault-secrets # имя будущего секрета kubernetes
  data:
    - secretKey: user # ключ секрета
      remoteRef:
        key: dev/app # путь до секрета в vault
        property: user # ключ секрета в vault
    - secretKey: password
      remoteRef:
        key: dev/app
        property: password