apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: app
  namespace: dev-app
spec:
  provider:
    vault:
      server: "http://vault.vault:8200" # адрес нашего vault. 
      #Складывается из имени сервиса и пространства имен.
      path: "projects" # имя kv
      version: "v2" # версия kv
      auth:
        kubernetes: # метод авторизации
          mountPath: "kubernetes"
          role: "read-secret" # заранее созданная роль в Vault для авторизации
          serviceAccountRef:
            name: "vault-auth" # имя нашего serviceAccount