# VaultStaticSecret:
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  annotations:
    meta.helm.sh/release-name: service-test
    meta.helm.sh/release-namespace: service-test
  labels:
    app.kubernetes.io/managed-by: Helm
  name: service-test
  namespace: service-test
spec:
  destination:
    create: true
    name: service-test-secret # создается Opaque secret с именем "service-test-secret"
    type: Opaque
  hmacSecretData: true # Данное поле определяет, будет ли высчитываться HMAC данных секрета, значение "MAC" будет храниться в поле "status.secretMAC" этого ресурса и будет использоваться для обнаружения отклонений. РЕКОМЕНДУЕТСЯ ВКЛЮЧИТЬ ЭТУ ФУНКЦИЮ ДЛЯ ОБЕСПЕЧЕНИЯ СОГЛАСОВАННОСТИ ДАННЫХ SECRET С VAULT 
  mount: secret # точка монтирования секретов
  path: test/services/service-test # path, по которому забираем секрет
  type: kv-v2 # тип секрета
  vaultAuthRef: service-test # ссылка на ресурс "VaultAuth", для авторизации в Vault