apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: service-test-csi
  namespace: service-test
spec:
  parameters:
    objects: |
      - objectName: "TEST_1" # имя объекта для маппинга секретов из Vault в Opaque secrets k8s
        secretPath: secret/data/test/services/service-test # Путь в Vault, по которому лежат секреты
        secretKey: TEST_1 # имя секрета из Vault
    roleName: service-test
    vaultAddress: http://vault.vault.svc:8200
  provider: vault
  secretObjects:
    - data:
        - key: TEST_1 # Ключ по которому создастся в Opaque secret "service-test-secret" секрет из Vault
          objectName: TEST_1 # имя объекта для маппинга секретов из Vault в Opaque secrets k8s
      secretName: service-test-secret # Имя Opaque secret, который создастся в k8s
      type: Opaque